# Generated by Django 4.2.6 on 2023-10-07 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('ticker', models.CharField()),
                ('prince', models.FloatField()),
                ('shares', models.IntegerField()),
                ('costs', models.FloatField()),
                ('taxes', models.FloatField()),
                ('currencyPair', models.CharField()),
                ('comment', models.TextField(blank=True, max_length=250, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
