# Generated by Django 4.2.6 on 2023-10-10 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tradetables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ticker', models.CharField()),
                ('price', models.FloatField()),
                ('shares', models.IntegerField()),
                ('costs', models.FloatField()),
                ('taxes', models.FloatField()),
                ('currencyPair', models.CharField()),
                ('comment', models.TextField(blank=True, max_length=250, null=True)),
                ('tradeTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='tradetables.tradetable')),
            ],
        ),
    ]
