# Generated by Django 4.2.6 on 2023-10-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='prince',
            new_name='price',
        ),
    ]
