# Generated by Django 4.2.6 on 2023-10-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradetables', '0001_initial'),
        ('trades', '0002_rename_prince_trade_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='user',
        ),
        migrations.AddField(
            model_name='trade',
            name='tradeTable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='tradetables.tradetable'),
        ),
    ]
